INPUT_DIR: ../input/
MODELS_DIR: ../models/
SUBMISSIONS_DIR: ../submissions/

batch_size: 10
learning_rate: 0.0003
n_epochs: 15
n_workers: 8
early_stopping_patience: 3


n_folds: 5
images_size: 512x512
model_name: tf_efficientnet_b3_ns
experiment_name: exp_train_02
use_test_labels: false
seed: 42
device: cuda:0
folds_train_file: train_folds_stratified
