INPUT_DIR: ../input/
MODELS_DIR: ../models/
SUBMISSIONS_DIR: ../submissions/

batch_size: 32
learning_rate: 0.001
n_epochs: 20
n_workers: 8
early_stopping_patience: 5
reduce_lr_on_plateau_patience: 3
reduce_lr_on_plateau_factor: 0.2
weight_decay: 0.01

n_folds: 5
images_size: 256x256
model_name: tf_efficientnet_b3_ns
exp_train_name: exp_train_04
use_test_labels: false
seed: 42
device: cuda:0
folds_train_file: train_folds_groups
