INPUT_DIR: ../input/
MODELS_DIR: ../models/
SUBMISSIONS_DIR: ../submissions/
SMOOTHEDLABELS_DIR: ../input/pseudo-labels/smoothed-labels/

batch_size: 10
learning_rate: 0.0003
n_epochs: 5
n_workers: 8
early_stopping_patience: 3
reduce_lr_on_plateau_patience: 1
reduce_lr_on_plateau_factor: 0.5
weight_decay: 0.001

n_folds: 5
images_size: 512x512
model_name: tf_efficientnet_b3_ns
experiment_name: exp_train_02
seed: 42
device: cuda:0