INPUT_DIR: ../input/
MODELS_DIR: ../models/
SUBMISSIONS_DIR: ../submissions/
SMOOTHEDLABELS_DIR: ../input/pseudo-labels/smoothed-labels/

batch_size: 10
learning_rate: 0.001
n_epochs: 3
n_workers: 8
weight_decay: 0.001

n_folds: 5
images_size: 512x512
model_name: tf_efficientnet_b3_ns
exp_train_name: exp_train_02
seed: 42
device: cuda:0
folds_train_file: train_folds_stratified